const ADD_MESSAGE_SUCCESS = '[chat] ADD_MESSAGE_SUCCESS';
const DELETE_MESSAGE_SUCCESS = '[chat] DELETE_MESSAGE_SUCCESS';
const EDIT_MESSAGE_SUCCESS = '[chat] EDIT_MESSAGE_SUCCESS';

const FETCH_REQUEST = '[chat] FETCH_REQUEST';
const FETCH_SUCCESS = '[chat] FETCH_SUCCESS';
const FETCH_ERROR = '[chat] FETCH_ERROR';

export default {
  EDIT_MESSAGE_SUCCESS,
  ADD_MESSAGE_SUCCESS,
  DELETE_MESSAGE_SUCCESS,
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
};
